baseURL = "https://ali.anari.io/"
languageCode = "en-us"
title = "Ali Anari"
theme = "archie"
copyright = "© Ali Anari"
pygmentsstyle = "dracula"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
paginate=4

[params]
og_image = "https://ali.anari.io/og-image.png"
favicon = "/favicon.ico"
mode="toggle"
useCDN=true
description = "Personal website for Ali Anari"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/aanari"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Vitamins"
url = "/vitamins"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 5
